
import React from 'react';

export const TRANSLATIONS = {
  FR: {
    dashboard: "Tableau de Bord",
    creation: "Création Plantation",
    maintenance: "Entretien Production",
    harvest: "Récolte Régimes",
    production: "Production Huile",
    packaging: "Conditionnement",
    sales: "Ventes",
    cash: "Mouvements Caisse",
    stats: "Statistiques",
    users: "Gestion Utilisateurs",
    logout: "Déconnexion",
    searchPlaceholder: "Rechercher une opération, date...",
    recentActivities: "Activités Récentes",
    totalSales: "Total des Ventes",
    totalCosts: "Total des Coûts",
    netBalance: "Solde Net",
    addOperation: "Ajouter une Opération",
    login: "Connexion",
    username: "Nom d'utilisateur",
    password: "Mot de passe",
    role: "Rôle",
    admin: "Administrateur",
    employee: "Employé",
    tutorial: "Tutoriel interactif",
    aiAssistant: "Assistant IA",
    date: "Date",
    zone: "Zone",
    quantity: "Quantité",
    cost: "Coût",
    workers: "Ouvriers",
    observations: "Observations",
    save: "Enregistrer",
    cancel: "Annuler",
    product: "Produit",
    client: "Client",
    unitPrice: "Prix Unitaire",
    total: "Total",
    reason: "Motif",
    amount: "Montant",
    type: "Type",
    in: "Entrée",
    out: "Dépense",
    withdrawal: "Retrait",
    notifications: "Notifications",
    noNotifications: "Aucune notification",
    markAllRead: "Tout marquer comme lu",
    lowBalanceAlert: "Alerte : Solde de caisse faible !",
    tutorialTitle: "Centre d'Apprentissage Plameraie BST",
    tutorialSubtitle: "Maîtrisez tous les aspects de votre plantation en quelques minutes.",
    lessons: {
      intro: "Introduction & Navigation",
      creation: "Gestion de la Création",
      maintenance: "Maintenance & Entretien",
      harvest: "Récoltes & Logistique",
      finance: "Gestion de la Caisse",
      stats: "Analyse des Performances"
    },
    yield: "Rendement",
    rawMaterial: "Matière Première",
    processed: "Traité",
    produced: "Produit",
    oilOutput: "Huile Produite",
    inputWeight: "Poids Entrant",
    extractionRate: "Taux d'Extraction",
    batchHistory: "Historique des Lots",
    productionSteps: "Étapes de Transformation",
    avgYield: "Rendement Moyen",
    totalProcessed: "Total Matière Traitée",
    opLists: {
      CREATION: ["Abattage des arbres", "Défrichage", "Achat des plants", "Piquetage", "Trouaison", "Transport des plants", "Mise en terre", "Installation des protections", "Autre..."],
      MAINTENANCE: ["Redressage des plants", "Remplacement plants morts", "Sarclage", "Défrichage", "Lutte nuisibles/maladies", "Fertilisation", "Récoltes intermédiaires", "Autre..."],
      HARVEST: ["Coupe des régimes", "Ramassage des branches", "Ramassage des noix", "Raccourcissement pédoncules", "Préparation transformation", "Transport et stockage", "Autre..."],
      PRODUCTION: ["Séparation des éléments", "Traitement des noix", "Cuisson", "Pilage", "Extraction de l'huile", "Récupération sous-produits", "Autre..."]
    }
  },
  EN: {
    dashboard: "Dashboard",
    creation: "Plantation Creation",
    maintenance: "Maintenance",
    harvest: "Harvesting",
    production: "Oil Production",
    packaging: "Packaging",
    sales: "Sales",
    cash: "Cash Management",
    stats: "Statistics",
    users: "User Management",
    logout: "Logout",
    searchPlaceholder: "Search operation, date...",
    recentActivities: "Recent Activities",
    totalSales: "Total Sales",
    totalCosts: "Total Costs",
    netBalance: "Net Balance",
    addOperation: "Add Operation",
    login: "Login",
    username: "Username",
    password: "Password",
    role: "Role",
    admin: "Administrator",
    employee: "Employee",
    tutorial: "Interactive Tutorial",
    aiAssistant: "AI Assistant",
    date: "Date",
    zone: "Zone",
    quantity: "Quantity",
    cost: "Cost",
    workers: "Workers",
    observations: "Observations",
    save: "Save",
    cancel: "Cancel",
    product: "Product",
    client: "Client",
    unitPrice: "Unit Price",
    total: "Total",
    reason: "Reason",
    amount: "Amount",
    type: "Type",
    in: "Income",
    out: "Expense",
    withdrawal: "Withdrawal",
    notifications: "Notifications",
    noNotifications: "No notifications",
    markAllRead: "Mark all as read",
    lowBalanceAlert: "Alert: Low cash balance!",
    tutorialTitle: "Learning Center Plameraie BST",
    tutorialSubtitle: "Master every aspect of your plantation in minutes.",
    lessons: {
      intro: "Introduction & Navigation",
      creation: "Creation Management",
      maintenance: "Maintenance & Upkeep",
      harvest: "Harvests & Logistics",
      finance: "Cash Management",
      stats: "Performance Analysis"
    },
    yield: "Yield",
    rawMaterial: "Raw Material",
    processed: "Processed",
    produced: "Produced",
    oilOutput: "Oil Produced",
    inputWeight: "Input Weight",
    extractionRate: "Extraction Rate",
    batchHistory: "Batch History",
    productionSteps: "Processing Steps",
    avgYield: "Avg Yield",
    totalProcessed: "Total Processed",
    opLists: {
      CREATION: ["Tree Felling", "Clearing", "Sapling Purchase", "Staking", "Digging", "Sapling Transport", "Planting", "Protection Install", "Other..."],
      MAINTENANCE: ["Straightening plants", "Replanting dead ones", "Weeding", "Land clearing", "Pest control", "Fertilization", "Intermediate harvests", "Other..."],
      HARVEST: ["Cutting bunches", "Branch gathering", "Nut gathering", "Trimming stalks", "Processing prep", "Transport & Storage", "Other..."],
      PRODUCTION: ["Separation", "Nut treatment", "Cooking", "Crushing", "Oil extraction", "By-product recovery", "Other..."]
    }
  }
};

export const COLORS = {
  primary: "#166534", // Green-800
  secondary: "#fbbf24", // Amber-400 (Palm oil color)
  accent: "#ea580c", // Orange-600
  dark: "#0f172a"
};
