import React from 'react';

export const TRANSLATIONS = {
  FR: {
    dashboard: "Tableau de Bord",
    creation: "Création Plantation",
    maintenance: "Entretien Production",
    harvest: "Récolte Régimes",
    production: "Production Huile",
    packaging: "Conditionnement",
    sales: "Ventes",
    cash: "Mouvements Caisse",
    stats: "Statistiques",
    users: "Gestion Utilisateurs",
    logout: "Déconnexion",
    searchPlaceholder: "Rechercher une opération...",
    recentActivities: "Activités Récentes",
    totalSales: "Total des Ventes",
    totalCosts: "Total des Coûts",
    netBalance: "Solde Net",
    addOperation: "Ajouter une Opération",
    login: "Connexion",
    username: "Nom d'utilisateur",
    password: "Mot de passe",
    role: "Rôle",
    admin: "Administrateur",
    employee: "Employé",
    tutorial: "Guide & Aide",
    aiAssistant: "Assistant IA",
    date: "Date",
    zone: "Zone",
    quantity: "Quantité",
    cost: "Coût",
    workers: "Ouvriers",
    observations: "Observations",
    save: "Enregistrer",
    cancel: "Annuler",
    product: "Produit",
    client: "Client",
    unitPrice: "Prix Unitaire",
    total: "Total",
    reason: "Motif",
    amount: "Montant",
    type: "Type",
    in: "Entrée",
    out: "Dépense",
    withdrawal: "Retrait",
    notifications: "Notifications",
    noNotifications: "Aucune notification",
    markAllRead: "Tout marquer comme lu",
    tutorialTitle: "Centre d'Apprentissage BST",
    tutorialSubtitle: "Tout ce qu'il faut savoir pour gérer votre plantation.",
    
    // Nouveaux champs pour ProductionModule
    totalProcessed: "Matière traitée",
    oilOutput: "Huile produite",
    avgYield: "Rendement Moyen",
    extractionRate: "Taux d'extraction",
    produced: "Production",
    batchHistory: "Historique des Lots",
    rawMaterial: "Matière Première",
    
    opLists: {
      CREATION: ["Délimitation", "Piquetage", "Trouaison", "Mise en terre", "Arrosage initial", "Autre..."],
      MAINTENANCE: ["Désherbage manuel", "Élagage", "Épandage Engrais", "Traitement Phyto", "Nettoyage couronne", "Autre..."],
      HARVEST: ["Coupe des régimes", "Ramassage", "Transport Usine", "Égrappage", "Autre..."],
      PRODUCTION: ["Pesée", "Cuisson", "Pressage", "Clarification", "Filtration", "Autre..."],
      PACKAGING: ["Mise en bouteille 1L", "Conditionnement 5L", "Bidons 20L", "Étiquetage", "Autre..."]
    },
    
    superAdmin: {
      hello: "Bonjour, MiguelF",
      welcome: "Console de Maîtrise Plameraie BST",
      clientCount: "Clients Actifs",
      newClient: "Inscrire une nouvelle entreprise",
      activeClients: "Liste des Palmeraies",
      plantationName: "Nom de la Palmeraie",
      managerName: "Nom du Gérant",
      email: "Email de contact",
      generate: "Générer Code d'Accès",
      clientCode: "Code Client",
      status: "Paiement",
      actions: "Actions",
      success: "Compte créé !",
      giveCode: "Envoyez ce code au client :",
      defaultCreds: "* Identifiants : admin / admin",
      suspend: "Suspendre",
      reactivate: "Activer",
      noClients: "Aucun client enregistré."
    }
  },
  EN: {
    dashboard: "Dashboard",
    creation: "Plantation Creation",
    maintenance: "Maintenance",
    harvest: "Harvesting",
    production: "Oil Production",
    packaging: "Packaging",
    sales: "Sales",
    cash: "Cash Management",
    stats: "Statistics",
    users: "User Management",
    logout: "Logout",
    searchPlaceholder: "Search...",
    recentActivities: "Recent Activities",
    totalSales: "Total Sales",
    totalCosts: "Total Costs",
    netBalance: "Net Balance",
    addOperation: "Add Operation",
    login: "Login",
    username: "Username",
    password: "Password",
    role: "Role",
    admin: "Administrator",
    employee: "Employee",
    tutorial: "Help & Guide",
    aiAssistant: "AI Assistant",
    date: "Date",
    zone: "Zone",
    quantity: "Quantity",
    cost: "Cost",
    workers: "Workers",
    observations: "Observations",
    save: "Save",
    cancel: "Cancel",
    product: "Product",
    client: "Client",
    unitPrice: "Unit Price",
    total: "Total",
    reason: "Reason",
    amount: "Amount",
    type: "Type",
    in: "Income",
    out: "Expense",
    withdrawal: "Withdrawal",
    notifications: "Notifications",
    noNotifications: "No notifications",
    markAllRead: "Mark all as read",
    tutorialTitle: "BST Learning Center",
    tutorialSubtitle: "Master your plantation management.",
    
    totalProcessed: "Processed Material",
    oilOutput: "Oil Produced",
    avgYield: "Average Yield",
    extractionRate: "Extraction Rate",
    produced: "Production",
    batchHistory: "Batch History",
    rawMaterial: "Raw Material",

    opLists: {
      CREATION: ["Boundary Setting", "Staking", "Digging", "Planting", "Initial Watering", "Other..."],
      MAINTENANCE: ["Weeding", "Pruning", "Fertilizing", "Phyto Treatment", "Ring Cleaning", "Other..."],
      HARVEST: ["Bunch Cutting", "Collecting", "Transport to Factory", "De-bunching", "Other..."],
      PRODUCTION: ["Weighing", "Cooking", "Pressing", "Clarification", "Filtration", "Other..."],
      PACKAGING: ["Bottling 1L", "Packaging 5L", "Drums 20L", "Labeling", "Other..."]
    },
    
    superAdmin: {
      hello: "Hello, MiguelF",
      welcome: "Plameraie BST Master Console",
      clientCount: "Active Clients",
      newClient: "Register new company",
      activeClients: "Plantation List",
      plantationName: "Plantation Name",
      managerName: "Manager Name",
      email: "Contact Email",
      generate: "Generate Access Code",
      clientCode: "Client Code",
      status: "Payment",
      actions: "Actions",
      success: "Account created!",
      giveCode: "Send this code to client:",
      defaultCreds: "* Login: admin / admin",
      suspend: "Suspend",
      reactivate: "Activate",
      noClients: "No clients registered."
    }
  }
};

export const COLORS = {
  primary: "#166534", 
  secondary: "#fbbf24", 
  accent: "#ea580c", 
  dark: "#0f172a"
};